image: rikorose/gcc-cmake:latest

stages:
    - build
    - test

build:
    stage: build
    script: mkdir build && cd build && cmake .. && make
    artifacts:
        paths:
            - build/

test:
    stage: test
    script: cd build && make test
